use_frameworks!

platform :ios, '9.0'

target 'ShareTool_Example' do
  pod 'ShareTool', :path => '../'

  target 'ShareTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
